name: Continuous Integration

on: 
  push: 
    branches:
      - main
      - dev
  pull_request:

jobs:
  build-ruby:
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        ruby-version: [3.0.0-preview1]
    steps:
      - uses: actions/checkout@v2

      - name: Build Ruby ${{ matrix.ruby-version }}
        uses: ./.github/actions/build-ruby
        with:
          ruby-version: ${{ matrix.ruby-version }}
  
  mini-env:
    needs: build-ruby
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix: 
        rails: [norails, rails60, rails52, rails51, rails42, rails41, rails40, rails32, rails31, rails30]
        ruby-version: [ 3.0.0-preview1]
        exclude:
          - ruby-version: "3.0.0-preview1"
            rails: rails30
          - ruby-version: "3.0.0-preview1"
            rails: rails31
          - ruby-version: "3.0.0-preview1"
            rails: rails32
          - ruby-version: "3.0.0-preview1"
            rails: rails40
          - ruby-version: "3.0.0-preview1"
            rails: rails41
          - ruby-version: "3.0.0-preview1"
            rails: rails42
          - ruby-version: "3.0.0-preview1"
            rails: rails50
          - ruby-version: "3.0.0-preview1"
            rails: rails51
          - ruby-version: "3.0.0-preview1"
            rails: rails52
    steps:
      - uses: actions/checkout@v2

      - name: Build Ruby ${{ matrix.ruby-version }}
        uses: ./.github/actions/build-ruby
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Start mysql
        run: sudo systemctl start mysql

      - name: Run Unit Tests
        uses: nick-invision/retry@v1.0.0
        with:
          timeout_minutes: 20
          max_attempts: 2
          command:  bundle exec rake test:env[${{ matrix.rails }}] TESTOPTS="--verbose"
        env:
          DB_PORT: 3306
          MYSQL_PASSWORD: root

  multiverse:
    needs: build-ruby
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mongodb:
        image: mongo
        ports:
          - 27017:27017
      rabbitmq:
        image: rabbitmq:latest
        ports:
          - 5672:5672
        options: >-
          --health-cmd "rabbitmqctl node_health_check" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
      memcached:
        image: memcached:latest
        ports:
          - 11211:11211
        options: >-
          --health-cmd "timeout 5 bash -c 'cat < /dev/null > /dev/udp/127.0.0.1/11211'" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    strategy:
      fail-fast: false
      matrix:
        multiverse: [agent, api, background, background_2, database, httpclients, rails, rest, serialization, sinatra]
        ruby-version: [ 3.0.0-preview1]
        include:
          - ruby-version: "3.0.0-preview1"
            multiverse: infinite_tracing
        exclude:
          - ruby-version: "3.0.0-preview1"
            multiverse: api
          - ruby-version: "3.0.0-preview1"
            multiverse: sinatra

    steps:
      - uses: actions/checkout@v2

      - name: Build Ruby ${{ matrix.ruby-version }}
        uses: ./.github/actions/build-ruby
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Start mysql
        run: sudo systemctl start mysql

      - name: Run Multiverse Tests
        uses: nick-invision/retry@v1.0.0
        with:
          timeout_minutes: 30
          max_attempts: 4
          command:  bundle exec rake test:multiverse[group=${{ matrix.multiverse }},verbose]
        env:
          DB_PORT: 3306
          MYSQL_PASSWORD: root

      - name: Annotate errors
        if: ${{ failure() }}
        uses: ./.github/actions/annotate
