name: Infinite Tracing Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
# on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  infinite_tracing_test:
    runs-on: ubuntu-16.04
    env:
      LANG: C.UTF-8
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ["2.5.8", "2.6.6", "2.7.1"]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: ruby-cache
        with:
          path: ~/.rubies/ruby-${{ matrix.ruby-version }}
          key: v5-ruby-cache-${{ matrix.ruby-version }}
          restore-keys: |
            v5-ruby-cache-${{ matrix.ruby-version }}

      - name: Build Ruby ${{ matrix.ruby-version }}
        id: build-ruby
        uses: ./.github/actions/build-ruby
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Bundler install
        run: bundle install --path ~/.bundle

      - name: rake test
        run: bundle exec rake test:multiverse[group=infinite_tracing,verbose,nocache]
  