name: Multiverse Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: push

env:
  ruby-version: [ "2.0.0-p648", "2.1.10", "2.2.10", "2.3.8", "2.4.10", "2.5.8", "2.6.6", "2.7.1", "jruby-9.2.12.0" ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_ruby:
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        ruby-version: ${{ env.ruby-version }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: ruby-cache
        with:
          path: ~/.rubies/ruby-${{ matrix.ruby-version }}
          key: v5-ruby-cache-${{ matrix.ruby-version }}
          restore-keys: |
            v5-ruby-cache-${{ matrix.ruby-version }}

      - name: Build Ruby ${{ matrix.ruby-version }}
        id: build-ruby
        uses: ./.github/actions/build-ruby
        with:
          ruby-version: ${{ matrix.ruby-version }}
  
  multiverse_test:
    needs: build_ruby
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379
      mongodb:
        image: mongo
        ports:
          - 27017:27017
      rabbitmq:
        image: rabbitmq:latest
        ports:
          - 5672:5672
        options: --health-cmd "rabbitmqctl node_health_check" --health-interval 10s --health-timeout 5s --health-retries 5
      memcached:
        image: memcached:latest
        ports:
          - 11211:11211
        options: --health-cmd "timeout 5 bash -c 'cat < /dev/null > /dev/udp/127.0.0.1/11211'" --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      LANG: C.UTF-8
    strategy:
      fail-fast: false
      matrix:
        multiverse: [agent, api, background, background_2, database, httpclients, rails, rest, serialization, sinatra]
        ruby-version: ${{ env.ruby-version }}
        exclude:
          - ruby-version: "2.7.1"
            multiverse: api
          - ruby-version: "2.7.1"
            multiverse: sinatra
          - ruby-version: "jruby-9.2.12.0"
            multiverse: agent
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: ruby-cache
        with:
          path: ~/.rubies/ruby-${{ matrix.ruby-version }}
          key: v5-ruby-cache-${{ matrix.ruby-version }}
          restore-keys: |
            v5-ruby-cache-${{ matrix.ruby-version }}

      - name: Build Ruby ${{ matrix.ruby-version }}
        id: build-ruby
        uses: ./.github/actions/build-ruby
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: install libraries
        run: sudo apt-get install libsasl2-dev libxml2-dev libxslt1-dev 
        
      - name: install libcurl
        run: sudo apt-get install libcurl4-openssl-dev

      - name: install more libraries
        run: sudo apt-get install libgmp3-dev openssl libssl-dev build-essential haveged

      - name: Bundler install
        run: bundle install 

      - name: Start mysql
        run: sudo systemctl start mysql

      - name: rake test
        run: bundle exec rake test:multiverse[group=${{ matrix.multiverse }},verbose,nocache]
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          MYSQL_ROOT_PASSWORD: root