name: tag practice

on: [push]


jobs:
  practice:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Tag new version
      run: |
        if [ $(git tag -l testtag) ]; then
          echo "Tag already created for this version"
        else
          git tag testtag
          git push origin testtag
        fi
